title: Joshua B. Evans
email: jbe25@bath.ac.uk
description: Personal website of Joshua B. Evans, lecturer in computer science and artificial intelligence at the University of Bath.
image: /assets/images/profile_pic.png

# No theme (use own layouts and styles).
#theme: none

# Plugins list.
plugins:
  - jekyll-feed
  - jekyll-paginate-v2
  - jekyll-scholar
  - jekyll-seo-tag
  - jekyll-sitemap

markdown: kramdown
highlighter: rouge

# Build settings.
sass:
  style: compressed

defaults:
  - scope: { path: "", type: "posts" }
    values:
      layout: post
  - scope: { path: "", type: "pages" }
    values:
      layout: page

# Custom variables.
author:
  name: Joshua B. Evans
  affiliation: University of Bath
  email: jbe25@bath.ac.uk
socials:
  twitter: TheJEvns
  github: Ueva

# Exclude from processing.
exclude:
  - serve.ps1
  - serve.ps1
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
