title: Joshua B. Evans
email: jbe25@bath.ac.uk
description: Personal website of Joshua B. Evans, lecturer in artificial intelligence at the University of Bath.
baseurl: ""
url: "https://people.bath.ac.uk/jbe25"

# No theme (use own layouts and styles).
#theme: none

# Plugins list.
plugins:
  - jekyll-feed
  - jekyll-paginate-v2
  - jekyll-scholar
  - jekyll-seo-tag
  - jekyll-sitemap

markdown: kramdown
highlighter: rouge

# Build settings.
sass:
  style: compressed

defaults:
  - scope: { path: "", type: "posts" }
    values:
      layout: post
  - scope: { path: "", type: "pages" }
    values:
      layout: page

# Custom variables.
author:
  name: Joshua B. Evans
  affiliation: University of Bath
  email: jbe25@bath.ac.uk
socials:
  twitter: TheJEvns
  github: Ueva

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
