title: Joshua B. Evans
email: jbe25@bath.ac.uk
description: Joshua B. Evans is a lecturer at the University of Bath, where his research focuses on hierarchical reinforcement learning, skill discovery, and other aspects of artificial intelligence and machine learning.
image: /assets/images/profile_pic.png

# No theme (use own layouts and styles).
#theme: none

# Plugins list.
plugins:
  - jekyll-feed
  - jekyll-paginate-v2
  - jekyll-scholar
  - jekyll-seo-tag
  - jekyll-last-modified-at
  - jekyll-sitemap

markdown: kramdown
highlighter: rouge

# Build settings.
sass:
  style: compressed

defaults:
  - scope: { path: "", type: "posts" }
    values:
      layout: post
  - scope: { path: "", type: "pages" }
    values:
      layout: page
  # Keep shared papers accessible without listing them in the sitemap.
  - scope: { path: "assets/papers" }
    values:
      sitemap: false

# Custom variables.
author:
  name: Joshua B. Evans
  affiliation: University of Bath
  email: jbe25@bath.ac.uk
socials:
  twitter: TheJEvns
  github: Ueva

# Exclude from processing.
exclude:
  - serve.ps1
  - serve.ps1
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
